### ISSUE TITLE
Why haven't deepin-related packages been updated for 2 years?

### ISSUE THREAD

**Issue by fusion809** [gentoo-zh/overlay#341]
Hi,

I have some interest in forking DDE-related packages from this repo and updating them myself, but I thought I should ask why you, @microcai, haven't updated them in case there is some dependency or other issue I should know about. I hope my phrasing doesn't seem antagonistic, I love DDE but I also love Gentoo-based systems like my current OS, Sabayon Linux. 

Thanks for your time,
Brenton

**Comment by biergaizi** [comment]
No, you shouldn't ask for @microcai at all. He is neither the contributor nor the maintainer of Deepin-related packages. **The maintainer has stopped updating the packages 2 years ago, and left the development 1 year ago**, and none of us understands the upstream well enough to maintain them.

**Comment by biergaizi** [comment]
This question had been discussed at the beginning of this year, in #249. 

At a result, in commit 7b9b4d9c0c8e534b296b4c8407f488660928cfa8, all Deepin-related packages have been masked to prevent them be installed by the users by accident. The conclusion of previous discussion is that **if the maintainer would not come back at the end of 2015, all Deepin-related packages will be removed**.

**Comment by biergaizi** [comment]
Finally, thanks for your interest on all Deepin-related packages. We will be very glad to accept your contribution if you want to get involved and be the maintainer of Deepin Desktop Environment of gentoo-zh. :+1:

**Comment by biergaizi** [comment]
If you want to start maintaining them, be aware of the build systems/scripts of DDE. I haven't check DDE since February, but what I have seen is that they were using very brute-force scripts and caused extra troubles, for example, they call `sudo` during the compilation.

I knew the development of DDE starts to get on track in this year, hopefully most of the problems have been eliminated.

**Comment by biergaizi** [comment]
BTW, you may also like to check the unfinished pull request #290, which is submit in April.

**Comment by fusion809** [comment]
Well I was going to give it a shot, but I must admit my knowledge of ebuilds is fairly limited, so most of what I would be doing is polishing existing ebuilds and replacing problematic ebuilds with binary ones (that is, ones that installing the component in question using the Debian packages used by Deepin). I know PKGBUILDS (for Arch) significantly better than I know ebuilds.

**Comment by fusion809** [comment]
Oh and one more thing, I don't speak any language other than English, I know this overlay is meant for Chinese/Taiwanese Gentoo users so I'm afraid that's another reason why I felt maybe forking this repo would work best for me.

**Comment by biergaizi** [comment]
> But I must admit my knowledge of ebuilds is fairly limited [...] I know PKGBUILDS (for Arch) significantly better than I know ebuilds.

In fact if you have `PKGBUILD`s for a package it would be easily to write `ebuild`s since most problems have been addressed already. The biggest difference is that `ebuild`s have too many standardize `eclass`es and tricks to deal with common issues, such as ambiguous `#!/usr/bin/python` shebang. Newcomers have to figure them out, as a quick start you can reference all `ebuild`s from Portage tree and this repo, and of course, Gentoo Devmanual.

> what I would be doing is polishing existing ebuilds

That will be a good start.

> replacing problematic ebuilds with binary ones (that is, ones that installing the component in question using the Debian packages used by Deepin.
- If it's a proprietary package, go on, just don't forget about to copy the license to `licenses/` and set the `LICENSE` properly.
- if you get into some critical issues about the source, use a binary package instead won't be a prefect solution, but I won't complain about it, if it seems the only way. Just take care of `KEYWORDS`, ABI and `.so`. We need more discussions when there is a specific issue. 

> I don't speak any language other than English

Most of us can use basic English for conversation, and...

> this overlay is meant for Chinese/Taiwanese Gentoo users so I'm afraid that's another reason why I felt maybe forking this repo would work best for me.

Well, that's true. Deepin is a local project at the beginning thus it will appear at gentoo-_zh_. But, overall, although localization is one of the roles of this repo, this overlay is not limited to localization, basically it just for people's demand. We are adding all types of packages to make our life easier.

You could fork it at the first place, if DDE-stuff get more complicated, it's your choice to maintain a separate overlay such as `deepin-overlay`. But I'm glad to see if these packages in `gentoo-zh` can be commited back and get maintained.

**Comment by fusion809** [comment]
[Here](https://github.com/fasheng/arch-deepin/tree/master/pkgbuild)'s a GitHub repo containing PKGBUILDS for Deepin. These PKGBUILDS are up-to-date and I have managed to install them on an Arch VM. Do you know any guides for converting PKGBUILDS to ebuilds?

**Comment by biergaizi** [comment]
I think there is no guide about it, and if I wrote it down, it would be another series of devmanuals.

But in brief, the reason I said a `PKGBUILD` is really helpful is that a `PKGBUILD` tells a lot of the package. For example, if you just have a git repo, you won't know the story of the packages. But if you have a `PKGBUILD`, you can easily learn:
- The build system does the package use, e.g. autotools/cmake
- Any patch required to build the packages, e.g. `0001-fix-stack-overflow.patch`
- Whether there is a problem of the compilation and how to workaround it, e.g. use a `sed` operation to fix some variables.

Then you'll write a equivalent `ebuild` for it. For example, `inherit autotools`, `epatch 0001-fix-stack-overflow.patch`, put the `sed` command in `src_prepare()`.

You should start with https://devmanual.gentoo.org for general `ebuild` writing.

**Comment by dlan17** [comment]
Hi I've seen biergaizi (Tom li) been quite helpful here, https://devmanual.gentoo.org is really good material for learning ebuilds. and if you have any question don't forget to ping us at freenode #gentoo-dev-help irc channel ;-)

**Comment by biergaizi** [comment]
Since all questions are answered, close it.

**Comment by zhtengw** [comment]
Hi, I was the maintainer of deepin-related packages in gentoo-zh. Recently, I rewrite the ebuilds for the key packages of Deepin Desktop Environment 15.3 and add them to a overlay named deepin. Should I merge these ebuilds into gentoo-zh or just leave them in [deepin-overlay](https://github.com/zhtengw/deepin-overlay)?

**Comment by biergaizi** [comment]
@zhtengw

If the packages can be constantly maintained, feel free to merge. 👍

**Comment by zhtengw** [comment]
Thank you @biergaizi. The deepin overlay was just accepted by overlays.gentoo.org. Any one who wants to test DDE can add this overlay with "layman -L && layman -a deepin". I will start to merge them into gentoo-zh when all the ebuilds get higher degree of completion.
